services:
  backend:
    container_name: myrecipes-backend
    image: myrecipes-backend
    build:
      context: .
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/myRecipes
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=changeit
      #- SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - app

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: changeit
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - app
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - app
    depends_on:
      - db
    restart: unless-stopped

networks:
  app:
    driver: bridge

volumes:
  backend:
  postgres:
  pgadmin:
